# Generated by Django 5.2.1 on 2025-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_payment_phone_number_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_status',
            field=models.BooleanField(default=True),
        ),
    ]
